module.exports = {
  env: {
    VOTING_FACTORY_LOCALHOST: process.env.VOTING_FACTORY_LOCALHOST,
    VOTING_HANDLER_LOCALHOST: process.env.VOTING_HANDLER_LOCALHOST,
    INSTANCES_LIST_LOCALHOST: process.env.INSTANCES_LIST_LOCALHOST,
    VOTING_FACTORY_MUMBAI: process.env.VOTING_FACTORY_MUMBAI,
    VOTING_HANDLER_MUMBAI: process.env.VOTING_HANDLER_MUMBAI,
    INSTANCES_LIST_MUMBAI: process.env.INSTANCES_LIST_MUMBAI,
    VOTING_FACTORY_FUJI: process.env.VOTING_FACTORY_FUJI,
    VOTING_HANDLER_FUJI: process.env.VOTING_HANDLER_FUJI,
    INSTANCES_LIST_FUJI: process.env.INSTANCES_LIST_FUJI,
  },
};
