module.exports = {
  env: {
    VOTING_FACTORY_LOCALHOST: process.env.VOTING_FACTORY_LOCALHOST,
    VOTING_FACTORY_MUMBAI: process.env.VOTING_FACTORY_MUMBAI,
    VOTING_HANDLER_LOCALHOST: process.env.VOTING_HANDLER_LOCALHOST,
    VOTING_HANDLER_MUMBAI: process.env.VOTING_HANDLER_MUMBAI,
  },
};
